'use strict';
// Advertiser claims researched 27 September 2026; no on-site verification.
const LandCatalog = [
  {
    "id": "land-kw55379",
    "title": "Lagoa · Santo Isidoro",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 135000,
    "area": 11062,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser describes a rural plot with a sea view in Lagoa.",
    "note": "Rural land; no residential approval established.",
    "sourceURL": "https://www.kwportugal.pt/pt/Imovel/Venda/Terreno/Lisboa/Mafra/Santo-Isidoro/55379",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-cc1003083",
    "title": "Casal da Serra · Sobreiro",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 65000,
    "area": 2500,
    "planning": "Rural / non-buildable",
    "view": "Distant / horizon",
    "evidence": "Advertiser describes a sea view on the horizon.",
    "note": "Agricultural / leisure use advertised; dirt-road access.",
    "sourceURL": "https://casacerta.pt/imovel/1003083/terreno-para-venda-em-mafra",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-iv19182944",
    "title": "Baleia · Carvoeira",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 60000,
    "area": 4625,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "The listing title explicitly advertises a sea view.",
    "note": "Rural plot; construction rights not established. Title evidence only; confirm the view on site.",
    "sourceURL": "https://www.imovirtual.com/pt/anuncio/terreno-rustico-com-4-625-m-vista-mar-baleia-carvoeira-mafra-ID1iumk",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-iad136815",
    "title": "Ericeira · near Praia do Sul",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 299000,
    "area": 183,
    "planning": "Approval advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes a sea view, 300 m from Praia do Sul.",
    "note": "Approved house project claimed; obtain the decision and valid licence.",
    "sourceURL": "https://www.iadportugal.pt/anuncio/terreno-venda-ericeira-183m2/r136815",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34571797",
    "title": "Ericeira Sul · 400 m² lot",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 350000,
    "area": 400,
    "planning": "Approval advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes an open sea view from the plot.",
    "note": "353.7 m² house project; advertiser says paid licence valid until 18 November 2027. Verify documentation.",
    "sourceURL": "https://www.idealista.pt/imovel/34571797/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35049927",
    "title": "Caminho do Rio da Mina · Lagoa",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 650000,
    "area": 1100,
    "planning": "Approval advertised",
    "view": "Panoramic",
    "evidence": "Advertiser describes panoramic sea-facing views.",
    "note": "380 m² house and licence advertised. Project renders do not show completed buildings; construction excluded.",
    "sourceURL": "https://www.idealista.pt/imovel/35049927/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34851294",
    "title": "Rua da Igreja · Santo Isidoro",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 1900000,
    "area": 57880,
    "planning": "Conflicting / unclear",
    "view": "Ocean view",
    "evidence": "Advertiser explicitly states the land has a sea view.",
    "note": "Portal labels non-buildable but description refers to a 2004 PIP. No current approval established.",
    "sourceURL": "https://www.idealista.pt/imovel/34851294/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-rm121011438132",
    "title": "Rua 25 de Abril · Igreja Nova",
    "municipality": "Mafra",
    "district": "Lisbon",
    "price": 482500,
    "area": 2500,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes sea views from the land.",
    "note": "Up to 750 m² development claimed; obtain current municipal confirmation.",
    "sourceURL": "https://remax.pt/pt/imoveis/venda-terreno-tmafra-igreja-nova-e-cheleiros/121011438-132",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35009406",
    "title": "Alto do Valongo · Sobreiro Curvo",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 52500,
    "area": 6341,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertised as rural land with sea views over the Maceira valley.",
    "note": "Non-buildable listing. Water and electricity claimed. Matching duplicate advert counted once.",
    "sourceURL": "https://www.idealista.pt/imovel/35009406/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34647235",
    "title": "Póvoa de Penafirme · 700 m²",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 118000,
    "area": 700,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Agent reference MTL3265 explicitly advertises sea views.",
    "note": "Up to 175 m² / two floors claimed. May overlap the 1,400 m² offering MTL3265B; confirm parcel boundaries.",
    "sourceURL": "https://www.idealista.pt/imovel/34647235/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34647256",
    "title": "Póvoa de Penafirme · 1,400 m²",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 185000,
    "area": 1400,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Agent reference MTL3265B explicitly advertises sea views.",
    "note": "Up to two houses / 350 m² claimed. May combine the 700 m² offering; do not assume independent parcels.",
    "sourceURL": "https://www.idealista.pt/imovel/34647256/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35125364",
    "title": "A dos Cunhados · coastal panorama",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 160000,
    "area": 16520,
    "planning": "Conflicting / unclear",
    "view": "Panoramic",
    "evidence": "Advertiser describes views of Santa Rita beach, Berlengas and Santa Cruz.",
    "note": "Portal says non-buildable; description claims 480 m² urbanisable and ruins. Resolve zoning before valuation.",
    "sourceURL": "https://www.idealista.pt/imovel/35125364/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34977116",
    "title": "Sobreiro Curvo · development land",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 595000,
    "area": 8960,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes a sea view near Santa Cruz.",
    "note": "PIP submitted for nine houses; submission is not approval.",
    "sourceURL": "https://www.idealista.pt/imovel/34977116/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-rm12587111524",
    "title": "Rua do Lugar de Baixo · São Pedro da Cadeira",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 430000,
    "area": 2840,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "RE/MAX describes sea views from this 2,840 m² plot.",
    "note": "PIP in preparation for five houses. Another matching portal advert asks €450,000; confirm the actual asking price.",
    "sourceURL": "https://remax.pt/pt/imoveis/venda-terreno-ttorres-vedras-sao-pedro-da-cadeira/125871115-24",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35138277",
    "title": "Avenida Alto da Vela · Santa Cruz",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 480000,
    "area": 540,
    "planning": "Approval advertised",
    "view": "Oceanfront",
    "evidence": "Advertised on the first line of the sea at Santa Cruz.",
    "note": "Approved house and paid licence awaiting collection claimed. Other matching ads differ on price/licence; verify.",
    "sourceURL": "https://www.idealista.pt/imovel/35138277/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34204824",
    "title": "Rua do Moinho, 14 · Torres Vedras",
    "municipality": "Torres Vedras",
    "district": "Lisbon",
    "price": 89000,
    "area": 1130,
    "planning": "Potential advertised",
    "view": "Distant / horizon",
    "evidence": "Advertiser says the western coastline is visible on clear days.",
    "note": "Urban construction potential claimed. Weather-dependent distant view; indexed snapshot requires current-price confirmation.",
    "sourceURL": "https://www.idealista.pt/pro/mypropertygere-imobiliaria/imovel/34204824/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-33164220",
    "title": "Estrada do Vale Bravo · Atalaia",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 400000,
    "area": 1450,
    "planning": "Approval advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes a four-house project with sea views.",
    "note": "Project approved and licence ready to collect claimed; confirm view from ground and future floors.",
    "sourceURL": "https://www.idealista.pt/imovel/33164220/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-29411935",
    "title": "Atalaia · 22,920 m²",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 300000,
    "area": 22920,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertised as construction land with sea views, 700 m from the beach.",
    "note": "Other snapshots quote €375,000 and project approval. Confirm current price and approval status.",
    "sourceURL": "https://www.idealista.pt/imovel/29411935/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34885485",
    "title": "Rua 8 de Dezembro · Atalaia",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 129000,
    "area": 720,
    "planning": "Approval advertised",
    "view": "Ocean view",
    "evidence": "Advertiser explicitly states a sea view.",
    "note": "Approved T3 house project with 208 m² claimed; verify approved plans and licence.",
    "sourceURL": "https://www.idealista.pt/imovel/34885485/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-32077224",
    "title": "Atalaia · two-house project",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 220000,
    "area": 2891,
    "planning": "Approval advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes urban land with sea views.",
    "note": "Area conflict: heading 2,891 m², description 2,390 m². Two V4 houses with shared pool advertised; confirm survey.",
    "sourceURL": "https://www.idealista.pt/imovel/32077224/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34891179",
    "title": "Rua do Sargaçalinho · Atalaia",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 120000,
    "area": 347,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes an open sea view.",
    "note": "Heading 347 m² versus description 346 m². Building viability explicitly subject to municipal confirmation.",
    "sourceURL": "https://www.idealista.pt/imovel/34891179/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-33859005",
    "title": "Atalaia · 3,960 m²",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 350000,
    "area": 3960,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes open sea and countryside views.",
    "note": "Recent directory €350,000 versus older detail snapshot €370,000. Confirm current price and construction limits.",
    "sourceURL": "https://www.idealista.pt/imovel/33859005/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34098930",
    "title": "Avenida 24 de Junho",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 495000,
    "area": 2320,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser describes a sea view near Praia da Areia Branca.",
    "note": "Portal labels non-buildable despite residential surroundings; do not infer permission from neighbouring houses.",
    "sourceURL": "https://www.idealista.pt/imovel/34098930/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-veigas642137",
    "title": "Ribamar · views toward Berlengas",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 330000,
    "area": 1945,
    "planning": "Conflicting / unclear",
    "view": "Panoramic",
    "evidence": "Agent describes views of the ocean, Berlengas and countryside.",
    "note": "Well and two road accesses advertised. Residential approval not established. Matching Nestenn listing counted once.",
    "sourceURL": "https://www.veigas.eu/pt/detalhe-propriedade/terreno-vista-mar-lourinha-ribamar-agricultura/642137",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-era130250026",
    "title": "Estrada da Areia Branca",
    "municipality": "Lourinhã",
    "district": "Lisbon",
    "price": 320000,
    "area": 3080,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser explicitly describes sea views from the land.",
    "note": "Only part of the parcel is described as allowing construction; confirm footprint and limits.",
    "sourceURL": "https://www.netanuncio.pt/Terreno/Lisboa%2CLourinha/tem-Vista-para-Campo%2CVista-para-Mar%2CEscola%2CTransportes-Publicos/?UID=5cbd58bb-dfcd-11ef-a463-060000000052",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35099207",
    "title": "Almoçageme · Ulgueira",
    "municipality": "Sintra",
    "district": "Lisbon",
    "price": 195000,
    "area": 1280,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser describes views over the ocean and Serra de Sintra.",
    "note": "Non-buildable land with a tiny house advertised; legality not verified. Description rounds area to about 1,200 m².",
    "sourceURL": "https://www.idealista.pt/imovel/35099207/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34737892",
    "title": "Praia da Samarra · São João das Lampas",
    "municipality": "Sintra",
    "district": "Lisbon",
    "price": 14000,
    "area": 760,
    "planning": "Rural / non-buildable",
    "view": "Panoramic",
    "evidence": "Advertiser describes panoramic views over the Atlantic.",
    "note": "Non-buildable rural land. Confirm access, boundaries and coastal restrictions.",
    "sourceURL": "https://www.idealista.pt/imovel/34737892/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34053072",
    "title": "Rua da Picada · Magoito",
    "municipality": "Sintra",
    "district": "Lisbon",
    "price": 69000,
    "area": 3400,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser describes sea views over Praia do Magoito.",
    "note": "Older indexed snapshot. No permanent construction advertised; mobile-home permissions are not verified.",
    "sourceURL": "https://www.idealista.pt/imovel/34053072/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35335403",
    "title": "Alto da Parede · Rua Professor Branquinho",
    "municipality": "Cascais",
    "district": "Lisbon",
    "price": 1400000,
    "area": 940,
    "planning": "Potential advertised",
    "view": "Partial",
    "evidence": "Advertiser explicitly describes a partial sea view.",
    "note": "470 m² house potential claimed. Two-house alternative requires municipal confirmation.",
    "sourceURL": "https://www.idealista.pt/imovel/35335403/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35342696",
    "title": "Murtal · Avenida Almirante João de Azevedo Coutinho",
    "municipality": "Cascais",
    "district": "Lisbon",
    "price": 1890000,
    "area": 1620,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes an open view over the sea.",
    "note": "Includes an existing T3 house and pool. Development limits require municipal information; not vacant land.",
    "sourceURL": "https://www.idealista.pt/imovel/35342696/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-31424804",
    "title": "Malveira da Serra · Guincho hinterland",
    "municipality": "Cascais",
    "district": "Lisbon",
    "price": 600000,
    "area": 28960,
    "planning": "Conflicting / unclear",
    "view": "Panoramic",
    "evidence": "Advertiser describes broad views over the Atlantic.",
    "note": "Portal says urban, description places land in a natural park. No approved project established.",
    "sourceURL": "https://www.idealista.pt/imovel/31424804/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-iv19046900",
    "title": "Santo Amaro de Oeiras",
    "municipality": "Oeiras",
    "district": "Lisbon",
    "price": 2000000,
    "area": 998,
    "planning": "Conflicting / unclear",
    "view": "Ocean view",
    "evidence": "The listing title explicitly advertises a sea view.",
    "note": "Urban plot with an architect-designed project advertised; approval status and precise view need confirmation.",
    "sourceURL": "https://www.imovirtual.com/pt/anuncio/lote-de-998m2-com-projeto-de-autor-e-vista-mar-oeiras-ID1hUY4",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-rm1206119456",
    "title": "Porto Salvo",
    "municipality": "Oeiras",
    "district": "Lisbon",
    "price": 1550000,
    "area": 10680,
    "planning": "Conflicting / unclear",
    "view": "Ocean view",
    "evidence": "RE/MAX describes the rural parcel as having a sea view.",
    "note": "Urban / business surroundings do not establish building permission on the rural parcel.",
    "sourceURL": "https://remax.pt/pt/imoveis/venda-terreno-toeiras-porto-salvo/120611945-6",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34194709",
    "title": "Estrada do Robalo · Capuchos",
    "municipality": "Almada",
    "district": "Setúbal",
    "price": 579000,
    "area": 630,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes sea views and an open horizon over the fossil cliff.",
    "note": "Urban corner lot; house viability claimed, approval documents not reviewed.",
    "sourceURL": "https://www.idealista.pt/imovel/34194709/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34200758",
    "title": "Capuchos · two adjoining lots",
    "municipality": "Almada",
    "district": "Setúbal",
    "price": 1650000,
    "area": 1330,
    "planning": "Potential advertised",
    "view": "Panoramic",
    "evidence": "Advertiser describes panoramic ocean views from the existing house.",
    "note": "Includes an existing house and two title articles. Advertised total construction allowance 439.2 m²; verify.",
    "sourceURL": "https://www.idealista.pt/imovel/34200758/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-32465277",
    "title": "Zambujal · Aiana",
    "municipality": "Sesimbra",
    "district": "Setúbal",
    "price": 100000,
    "area": 3750,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser describes views of the sea, Lisbon and Cascais coastline.",
    "note": "Agricultural / forest zone. Only about 18.75 m² agricultural support claimed; no residential approval established.",
    "sourceURL": "https://www.idealista.pt/imovel/32465277/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34766539",
    "title": "N379 · Sentrão",
    "municipality": "Sesimbra",
    "district": "Setúbal",
    "price": 1849000,
    "area": 31326,
    "planning": "Rural / non-buildable",
    "view": "Panoramic",
    "evidence": "Advertiser describes a bay view toward Ribeiro do Cavalo beach.",
    "note": "Two rural parcels; portal says non-buildable. Any alternative use needs confirmation.",
    "sourceURL": "https://www.idealista.pt/imovel/34766539/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35317279",
    "title": "Meco / Azóia · 15,700 m²",
    "municipality": "Sesimbra",
    "district": "Setúbal",
    "price": 580000,
    "area": 15700,
    "planning": "Approval advertised",
    "view": "Panoramic",
    "evidence": "Advertiser describes panoramic Atlantic views.",
    "note": "PIP for 165 m² house and pool claimed. Portal places it in Alto das Vinhas, description says Meco; exact location needs confirmation.",
    "sourceURL": "https://www.idealista.pt/imovel/35317279/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34955330",
    "title": "Aiana de Cima · near Meco",
    "municipality": "Sesimbra",
    "district": "Setúbal",
    "price": 1790000,
    "area": 16500,
    "planning": "Conflicting / unclear",
    "view": "Panoramic",
    "evidence": "Advertiser describes views over the ocean and Lisbon bay.",
    "note": "Development permissions and sale boundaries need confirmation; do not infer buildable area from plot size.",
    "sourceURL": "https://www.idealista.pt/imovel/34955330/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-32068022",
    "title": "Santiago · above the harbour",
    "municipality": "Sesimbra",
    "district": "Setúbal",
    "price": 2500000,
    "area": 2000,
    "planning": "Conflicting / unclear",
    "view": "Panoramic",
    "evidence": "Advertiser describes a 180-degree Atlantic and harbour view.",
    "note": "Planning decision and permitted construction area not established in this research.",
    "sourceURL": "https://www.idealista.pt/imovel/32068022/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34729807",
    "title": "Venda Nova · Charneca da Cotovia",
    "municipality": "Sesimbra",
    "district": "Setúbal",
    "price": 280000,
    "area": 2971,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser states a view over Lisbon and the sea.",
    "note": "Confirm ocean sightline rather than only estuary; displayed buildable area requires municipal verification.",
    "sourceURL": "https://www.idealista.pt/imovel/34729807/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-rm12344130537",
    "title": "Soltróia · lots 17 and 19",
    "municipality": "Grândola",
    "district": "Setúbal",
    "price": 5500000,
    "area": 3262,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "RE/MAX advertises two adjoining lots with sea views.",
    "note": "Combined sale: 1,619 m² plus 1,643 m². Two houses claimed; confirm which direction and floors have ocean views.",
    "sourceURL": "https://www.remax.pt/pt/imoveis/venda-terreno-tgrandola-carvalhal/123441305-37",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34566546",
    "title": "Rossinha · Melides",
    "municipality": "Grândola",
    "district": "Setúbal",
    "price": 975000,
    "area": 92500,
    "planning": "Conflicting / unclear",
    "view": "Panoramic",
    "evidence": "Advertiser describes countryside and sea views.",
    "note": "Includes a ruin; further construction confirmation is pending in the description despite urbanisable label.",
    "sourceURL": "https://www.idealista.pt/imovel/34566546/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34902700",
    "title": "Sobreiras Altas · Melides",
    "municipality": "Grândola",
    "district": "Setúbal",
    "price": 1600000,
    "area": 24000,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes a traditional estate with sea views.",
    "note": "Existing buildings about 300 m². Heading 24,000 m² versus description 2.43 ha; confirm surveyed area.",
    "sourceURL": "https://www.idealista.pt/pro/imomelides/imovel/34902700/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-33206361",
    "title": "EN261-2 · Melides hilltop",
    "municipality": "Grândola",
    "district": "Setúbal",
    "price": 1560000,
    "area": 90000,
    "planning": "Potential advertised",
    "view": "Panoramic",
    "evidence": "Advertiser describes a 270-degree outlook reaching the ocean horizon.",
    "note": "Urbanisable portal category; exact permitted development and licence not established.",
    "sourceURL": "https://www.idealista.pt/imovel/33206361/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-32267492",
    "title": "Travessa do Teixeira · Melides",
    "municipality": "Grândola",
    "district": "Setúbal",
    "price": 727000,
    "area": 60000,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes sea views from a six-hectare property.",
    "note": "Residential potential claimed; obtain current municipal confirmation of use and building limits.",
    "sourceURL": "https://www.idealista.pt/imovel/32267492/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-33243646",
    "title": "Melides · elevated six-hectare estate",
    "municipality": "Grândola",
    "district": "Setúbal",
    "price": 1500000,
    "area": 60000,
    "planning": "Conflicting / unclear",
    "view": "Distant / horizon",
    "evidence": "Advertiser says the sea is visible from the highest parts of the land.",
    "note": "Portal says non-buildable while description presents a house project. Confirm area, approvals and exact viewing points.",
    "sourceURL": "https://www.idealista.pt/imovel/33243646/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35061215",
    "title": "Rua da Nau São Miguel · Convento",
    "municipality": "Sines",
    "district": "Setúbal",
    "price": 275000,
    "area": 580,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes sea views from the residential plot.",
    "note": "House with basement and two upper levels claimed; obtain planning and licence documents.",
    "sourceURL": "https://www.idealista.pt/imovel/35061215/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-32565217",
    "title": "Daroeira · Porto Covo",
    "municipality": "Sines",
    "district": "Setúbal",
    "price": 1500000,
    "area": 53547,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "Advertiser describes land with a house to rehabilitate and sea views.",
    "note": "Includes existing buildings; verify legal reconstruction and any new-development limits.",
    "sourceURL": "https://www.idealista.pt/imovel/32565217/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-33545362",
    "title": "Courela do Castanhal",
    "municipality": "Sines",
    "district": "Setúbal",
    "price": 580000,
    "area": 61500,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser explicitly states views over the sea.",
    "note": "Non-buildable rural classification on portal; construction rights not established.",
    "sourceURL": "https://www.idealista.pt/imovel/33545362/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-34631140",
    "title": "M554 · three agricultural parcels",
    "municipality": "Sines",
    "district": "Setúbal",
    "price": 360000,
    "area": 225000,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser describes cleared land with a sea view.",
    "note": "Three 7.5 ha parcels sold together. No construction viability advertised; agricultural support only subject to approval.",
    "sourceURL": "https://www.idealista.pt/imovel/34631140/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35281476",
    "title": "Porto Covo · opposite Ilha do Pessegueiro",
    "municipality": "Sines",
    "district": "Setúbal",
    "price": 100000,
    "area": 20000,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser explicitly states sea views opposite Ilha do Pessegueiro.",
    "note": "Agricultural land; mobile homes or caravans explicitly subject to authority approval.",
    "sourceURL": "https://www.idealista.pt/imovel/35281476/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35185798",
    "title": "M554 · fenced 5,000 m² plot",
    "municipality": "Sines",
    "district": "Setúbal",
    "price": 137500,
    "area": 5000,
    "planning": "Rural / non-buildable",
    "view": "Ocean view",
    "evidence": "Advertiser describes sea views from a flat three-frontage plot.",
    "note": "Likely matching advert at €145,000 counted once. Confirm current price and parcel identity; non-buildable.",
    "sourceURL": "https://www.idealista.pt/imovel/35185798/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-35183313",
    "title": "Ademas · Santa Cruz",
    "municipality": "Santiago do Cacém",
    "district": "Setúbal",
    "price": 375000,
    "area": 56000,
    "planning": "Conflicting / unclear",
    "view": "Ocean view",
    "evidence": "Advertiser describes a rural parcel with sea views.",
    "note": "Heading 56,000 m² versus description six hectares; urbanisable label is not an approval. Confirm area and permissions.",
    "sourceURL": "https://www.idealista.pt/imovel/35183313/",
    "researchedAt": "2026-09-27"
  },
  {
    "id": "land-iv19258147",
    "title": "São Francisco da Serra",
    "municipality": "Santiago do Cacém",
    "district": "Setúbal",
    "price": 400000,
    "area": 31864.4,
    "planning": "Potential advertised",
    "view": "Ocean view",
    "evidence": "The agent listing title explicitly advertises a sea view.",
    "note": "Urban category on portal; full permissions and view must be confirmed with the agent.",
    "sourceURL": "https://www.imovirtual.com/pt/anuncio/terreno-com-vista-mar-em-sao-francisco-da-serra-ID1iNWh",
    "researchedAt": "2026-09-27"
  }
];
if(typeof module!=='undefined')module.exports=LandCatalog;
