'use strict';
const RefreshUI=(()=>{
 const stamp=v=>v?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:String(v).includes('T')?'short':undefined,timeZone:'Europe/Lisbon'}).format(new Date(v)):'No successful automatic scan yet';
 const actions='https://github.com/Bomaguiar/tejo-scout/actions/workflows/daily-scan.yml';
 function summary(){const r=RefreshStatus;return 'Last content update: '+stamp(r.lastSuccessfulContentUpdate||r.checkedAt)+' · Last scan: '+stamp(r.checkedAt)+' · '+(r.directlyObserved??0)+'/'+r.existingAttempted+' adverts directly observed · '+r.unavailable+' could not be checked'+(r.needsReview?' · '+r.needsReview+' need review':'')+'.';}
 function notice(){return '<div class="notice">'+icon('updates')+'<span>'+esc(summary())+' Current feeds require a successful advert check within 48 hours. Hidden adverts remain in the archive; seller availability and permits require confirmation.</span><a class="right textlink" href="#updates">Scan status →</a></div>';}
 function check(id){const r=RefreshStatus.records.find(x=>x.id===id);if(!r)return '';if(['removed','sold','reserved'].includes(r.status))return 'Checked '+stamp(r.checkedAt)+': '+r.status+' · '+(r.error||'Advert inactive')+'. Last known asking price retained.';return r.status==='observed'?'Advert fetched directly '+stamp(r.checkedAt)+'. Availability unconfirmed.':r.status==='source-snapshot'?'Snapshot reviewed '+stamp(r.checkedAt)+'; crawled '+r.sourceCrawlAge+' relative to review. Availability unconfirmed.':'Checked '+stamp(r.checkedAt)+': '+(r.error||'could not retrieve the advert')+'. Last good data retained; availability unknown.';}
 function panel(){const r=RefreshStatus,sources=r.sources||[];return '<section class="panel gap"><div class="panelhead"><h2>Automatic daily scan</h2><a class="button small" href="'+actions+'" target="_blank" rel="noopener noreferrer">Runs / scan now ↗</a></div><div class="panelbody"><p><b>Daily at 08:17 · Lisbon time</b> on GitHub Actions. Runs with your computer switched off. GitHub schedules can start late.</p><p>'+esc(summary())+'</p><p class="formula">'+esc(r.coverage||'Public source snapshots; incomplete coverage.')+'</p><a class="textlink" href="refresh-report.json" target="_blank" rel="noopener">Download latest source report ↗</a><div class="tablewrap"><table><thead><tr><th>SOURCE</th><th>EXISTING CHECKED</th><th>OBSERVED</th><th>DISCOVERY</th><th>STATUS</th></tr></thead><tbody>'+sources.map(s=>'<tr><td>'+esc(s.name)+'</td><td>'+s.existing+'</td><td>'+s.fetched+'</td><td>'+s.detailCandidates+' of '+s.discoveredURLs+' URLs</td><td>'+esc(s.errors+' listing errors; '+s.discoveryErrors.length+' discovery errors')+'</td></tr>').join('')+'</tbody></table></div><details><summary>Hidden or inactive adverts</summary>'+r.records.filter(x=>['unavailable','needs-review','removed','sold','reserved'].includes(x.status)).map(x=>'<p><a href="'+esc(x.sourceURL)+'" target="_blank" rel="noopener">'+esc(x.id)+'</a> · '+esc(x.error||'Source unavailable')+'</p>').join('')+'</details><details><summary>New agency matches and price moves</summary>'+(r.discovery||[]).filter(x=>x.status==='added').map(x=>'<p><a href="'+esc(x.sourceURL)+'" target="_blank" rel="noopener">'+esc(x.observation.title)+'</a> · '+money(x.observation.price)+' · '+esc(x.agency)+'</p>').join('')+(Array.isArray(r.priceChanges)?r.priceChanges:[]).map(x=>'<p><a href="'+esc(x.sourceURL)+'" target="_blank" rel="noopener">'+esc(x.id)+'</a> · '+money(x.from)+' → '+money(x.to)+'</p>').join('')+'</details><p class="formula">The scanner reads public pages and agency sitemaps with request limits. Missing prices, ambiguous areas, rentals and unsupported locations are rejected. Blocked pages are preserved with a warning. Sea views and planning are seller claims. The action link lets the repository owner run the workflow after signing in to GitHub.</p></div></section>';}
 return {summary,notice,check,panel,stamp};
})();
